services:
  db-dev: &db
    container_name: octopost-db-dev
    profiles:
      - dev
    image: postgres:alpine3.19
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: '/var/lib/postgresql/mydata'
    env_file:
      - .env.example
      - .env
    volumes:
      - db:/var/lib/postgresql/mydata
    networks:
      - octopost

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: octopost-api
    profiles:
      - prod
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-prod
    env_file:
      - .env.example
      - .env
    networks:
      - octopost

  db-prod:
    <<: *db
    container_name: octopost-db
    profiles:
      - prod

networks:
  octopost:
    driver: bridge

volumes:
  db:
