openapi: 3.0.0
info:
  title: Octopost API
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
    description: Development server
  - url: https://octopost-backend-production.up.railway.app/api
    description: Production server
tags:
  - name: user
    description: Operations about user
  - name: social-medias
    description: Operations about social medias
paths:
  /users:
    $ref: './features/user/user-create-path.yaml'
  /users/:id/accounts:
    $ref: './features/user/user-network-find-all.yaml'
  /auth/login:
    $ref: './features/auth/login-path.yaml'
  /auth/confirmation?token=:
    $ref: './features/auth/email-confirmation-path.yaml'
  /users/{id}:
    $ref: './features/user/find-user-by-id-path.yaml'
  /users/{userId}/accounts/{accountId}:
    $ref: './features/social-medias/remove-social-medias-from-user.yaml'
  /socialmedias:
    $ref: './features/social-medias/list-available-social-medias.yaml'

components:
  $ref: './shared/components/security-schemes.yaml'
